version: 2.1
executors:
  node12:
    docker:
      - image: circleci/node:12
commands:
  setup:
    description: "checkout and yarn install"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  test:
    executor: node12
    steps:
      - setup
      - run: yarn test
workflows:
  app:
    jobs:
      - test
